### PR TITLE
Added possibility to use fabricator as a builder from another project.

### PR DESCRIPTION
**Pull request by dietergeerts**
Hi, I added this possibility for multiple reasons. I added it in such a way that it still works as expected, but it can also be used from another project. If then this is a npm module, it can be used as a frame for the actual toolkits.

All feedback is very welcome!

### CODE REVIEW

**Comment by dietergeerts** [comment]
Hi, any comments would be welcome. I just want to know how you are looking at this possibility. I don't want yet another repo out there. Better to have one with the option of how to use it.

**Comment by LukeAskew** [comment]
@dietergeerts totally on my radar. I like the idea, just need time to give it a good review.

Hopefully I can carve out some time later this week. Thanks for putting this together!

**Comment by dietergeerts** [comment]
I don't know if you had the time to look at it, but maybe it's better to have this as a seperate project that is used to build a toolkit rather than start one from it? I created an npm module for it and will try to keep it in sync with the original fabricator (this project). That way, people will be able to choose how they would like to use fabricator. I hope this is ok?

**Comment by LukeAskew** [comment]
Hey @dietergeerts, sorry just been cranking at work recently, so I haven't had a ton of time to look at stuff.

From the bits of this PR that I've read, I think you're right that it might be better as a separate project. I am fine with however you want to manage that. I'd still love to give feedback as your project progresses. :sunglasses:

**Pull request closed without merging**
