### PR TITLE
Adding source maps

### PR DESCRIPTION
**Pull request by jonorherrington**
Adding source maps to make developing Sass faster, especially when using partials.

### CODE REVIEW

**Comment by LukeAskew** [comment]
Is there a benefit of writing to an external file rather than just inline as encoded data?

The latter would prevent maps from being distributed in a production build since the css minification removes comments.

**Comment by jonorherrington** [comment]
Good point @LukeAskew. I will make that small modification and commit. Thanks!

**Comment by jonorherrington** [comment]
@LukeAskew I have updated the code to account for the changes we talked about. Please take a look.

**Comment by LukeAskew** [comment]
Awesome :guitar: :+1: :gem:

**Pull request merged**
